// Table and field definitions shared by the Worker and the client.

export type Unit = 'ea' | 'lb';
export type ItemType = 'subkit' | 'bag' | 'part';
export type ItemStatus = 'expected' | 'received' | 'missing' | 'damaged' | 'backordered';
export type LocationType = 'bin' | 'shelf' | 'crate' | 'rack' | 'other';

export const ITEM_STATUSES: ItemStatus[] = ['expected', 'received', 'missing', 'damaged', 'backordered'];
export const PROBLEM_STATUSES: ItemStatus[] = ['missing', 'damaged', 'backordered'];
export const LOCATION_TYPES: LocationType[] = ['bin', 'shelf', 'crate', 'rack', 'other'];

interface Meta {
  id: number;
  version: number;
  updated_at: string;
  updated_by: string;
  deleted_at: string | null;
}

export interface Kit extends Meta {
  code: string;
  name: string;
  received_at: string | null;
}

export interface Location extends Meta {
  code: string;
  type: LocationType;
  description: string | null;
}

export interface Item extends Meta {
  kit_id: number;
  parent_id: number | null;
  item_type: ItemType;
  stock_code: string;
  search_key: string;
  description: string | null;
  qty: number;
  unit: Unit;
  vans_bin: string | null;
  status: ItemStatus;
  source: 'import' | 'manual';
  notes: string | null;
  sort_order: number;
  /** A photo of the part, by id. See photoObject(). */
  photo_key: string | null;
  /** How many arrived, when counted on receiving. Null: not counted (a received part arrived in full). */
  qty_received: number | null;
}

export interface Placement extends Meta {
  item_id: number;
  location_id: number;
  qty: number | null;
}

export interface PickList extends Meta {
  section: string;
  page: string | null;
  title: string | null;
}

export interface PickListLine extends Meta {
  pick_list_id: number;
  stock_code: string;
  search_key: string;
  qty_needed: number | null;
  pulled: number;
}

export interface Consumption extends Meta {
  item_id: number;
  qty: number;
  pick_list_id: number | null;
  note: string | null;
}

export interface Rows {
  kits: Kit;
  locations: Location;
  items: Item;
  placements: Placement;
  pick_lists: PickList;
  pick_list_lines: PickListLine;
  consumptions: Consumption;
}

export type TableName = keyof Rows;

/** Fields a client may write, per table. Meta fields are set by the server. */
export const WRITABLE: { [T in TableName]: readonly (keyof Rows[T] & string)[] } = {
  kits: ['code', 'name', 'received_at', 'deleted_at'],
  locations: ['code', 'type', 'description', 'deleted_at'],
  items: [
    'kit_id', 'parent_id', 'item_type', 'stock_code', 'search_key', 'description', 'qty', 'unit',
    'vans_bin', 'status', 'source', 'notes', 'sort_order', 'photo_key', 'qty_received', 'deleted_at',
  ],
  placements: ['item_id', 'location_id', 'qty', 'deleted_at'],
  pick_lists: ['section', 'page', 'title', 'deleted_at'],
  pick_list_lines: ['pick_list_id', 'stock_code', 'search_key', 'qty_needed', 'pulled', 'deleted_at'],
  consumptions: ['item_id', 'qty', 'pick_list_id', 'note', 'deleted_at'],
};

export const TABLE_NAMES = Object.keys(WRITABLE) as TableName[];

/** Part photos are stored by a random id: a full-size JPEG and a small thumbnail. */
export const PHOTO_KEY = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
export const photoObject = (warehouseId: string, key: string, size: 'full' | 'thumb') =>
  `w/${warehouseId}/parts/${key}${size === 'thumb' ? '-thumb' : ''}.jpg`;

export type Fields<T extends TableName> = Partial<Omit<Rows[T], 'id' | 'version' | 'updated_at' | 'updated_by'>>;

export type Op =
  | { op: 'insert'; table: TableName; id: number; fields: Record<string, unknown> }
  | { op: 'update'; table: TableName; id: number; fields: Record<string, unknown> }
  | { op: 'delete'; table: TableName; id: number };

export interface Mutation {
  /** Client-generated UUID. The server applies each id at most once. */
  id: string;
  label: string;
  created_at: string;
  ops: Op[];
}

export interface MutationResult {
  id: string;
  status: 'applied' | 'duplicate' | 'rejected';
  error?: string;
}

export interface MutationsResponse {
  results: MutationResult[];
  version: number;
}

export interface SyncResponse {
  version: number;
  full: boolean;
  rows: { [T in TableName]: Rows[T][] };
}

/**
 * Row ids are generated by whoever creates the row (client or server), so offline
 * inserts never need id remapping. Random in [2^32, 2^52]: safe JS integers, and
 * collisions are negligible at a few thousand rows.
 */
export function newId(): number {
  const buf = new Uint32Array(2);
  crypto.getRandomValues(buf);
  const high = buf[0] & 0xfffff; // 20 bits
  return high * 0x100000000 + buf[1] + 0x100000000;
}
